using System;
using System.IO;
using System.Text;
using System.Numerics;
using System.Linq;
using System.Collections.Generic;

namespace SiphoningStrike.Game.Events
{
    public enum EventID
    {
        OnDie                            = 0x00,
        OnKill                           = 0x01,
        OnChampionDie                    = 0x02,
        OnChampionKill                   = 0x03,
        OnChampionDoubleKill             = 0x04,
        OnChampionTripleKill             = 0x05,
        OnChampionQuadraKill             = 0x06,
        OnChampionPentaKill              = 0x07,
        OnChampionUnrealKill             = 0x08,
        OnFirstBlood                     = 0x09,
        OnDamageTaken                    = 0x0A,
        OnDamageGiven                    = 0x0B,
        OnSpellCast1                     = 0x0C,
        OnSpellCast2                     = 0x0D,
        OnSpellCast3                     = 0x0E,
        OnSpellCast4                     = 0x0F,
        OnSpellAvatarCast1               = 0x10,
        OnSpellAvatarCast2               = 0x11,
        OnGoldSpent                      = 0x12,
        OnGoldEarned                     = 0x13,
        OnItemConsumeablePurchased       = 0x14,
        OnCriticalStrike                 = 0x15,
        OnAce                            = 0x16,
        OnReincarnate                    = 0x17,
        OnDampenerKill                   = 0x18,
        OnDampenerDie                    = 0x19,
        OnDampenerRespawnSoon            = 0x1A,
        OnDampenerRespawn                = 0x1B,
        OnTurretKill                     = 0x1C,
        OnTurretDie                      = 0x1D,
        OnMinionKill                     = 0x1E,
        OnMinionDenied                   = 0x1F,
        OnNeutralMinionKill              = 0x20,
        OnSuperMonsterKill               = 0x21,
        OnHQKill                         = 0x22,
        OnHQDie                          = 0x23,
        OnHeal                           = 0x24,
        OnCastHeal                       = 0x25,
        OnBuff                           = 0x26,
        OnKillingSpree                   = 0x27,
        OnKillingSpreeSet1               = 0x28,
        OnKillingSpreeSet2               = 0x29,
        OnKillingSpreeSet3               = 0x2A,
        OnKillingSpreeSet4               = 0x2B,
        OnKillingSpreeSet5               = 0x2C,
        OnKillingSpreeSet6               = 0x2D,
        OnKilledUnitOnKillingSpree       = 0x2E,
        OnKilledUnitOnKillingSpreeSet1   = 0x2F,
        OnKilledUnitOnKillingSpreeSet2   = 0x30,
        OnKilledUnitOnKillingSpreeSet3   = 0x31,
        OnKilledUnitOnKillingSpreeSet4   = 0x32,
        OnKilledUnitOnKillingSpreeSet5   = 0x33,
        OnKilledUnitOnKillingSpreeSet6   = 0x34,
        OnDeathAssist                    = 0x35,
        OnQuit                           = 0x36,
        OnLeave                          = 0x37,
        OnReconnect                      = 0x38,
        OnGameStart                      = 0x39,
        OnPing                           = 0x3A,
        OnPingPlayer                     = 0x3B,
        OnPingBuilding                   = 0x3C,
        OnPingOther                      = 0x3D,
        OnEndGame                        = 0x3E,
        OnSpellLevelup1                  = 0x3F,
        OnSpellLevelup2                  = 0x40,
        OnSpellLevelup3                  = 0x41,
        OnSpellLevelup4                  = 0x42,
        OnItemPurchased                  = 0x43,
        OnSurrenderVoteStart             = 0x44,
        OnSurrenderVote                  = 0x45,
        OnSurrenderVoteAlready           = 0x46,
        OnSurrenderCountDown             = 0x47,
        OnSurrenderFailedVotes           = 0x48,
        OnSurrenderTooEarly              = 0x49,
        OnSurrenderAgreed                = 0x4A,
        OnSurrenderSpam                  = 0x4B,
        OnPause                          = 0x4C,
        OnPauseResume                    = 0x4D,
        OnMinionsSpawn                   = 0x4E,
        OnStartGameMessage1              = 0x4F,
        OnStartGameMessage2              = 0x50,
        OnAlert                          = 0x51,
        OnScoreboardOpen                 = 0x52,
        OnAudioEventFinished             = 0x53,
        OnNexusCrystalStart              = 0x54,
        OnCapturePointNeutralized_A      = 0x55,
        OnCapturePointNeutralized_B      = 0x56,
        OnCapturePointNeutralized_C      = 0x57,
        OnCapturePointNeutralized_D      = 0x58,
        OnCapturePointNeutralized_E      = 0x59,
        OnCapturePointCaptured_A         = 0x5A,
        OnCapturePointCaptured_B         = 0x5B,
        OnCapturePointCaptured_C         = 0x5C,
        OnCapturePointCaptured_D         = 0x5D,
        OnCapturePointCaptured_E         = 0x5E,
        OnVictoryPointThreshold1         = 0x5F,
        OnVictoryPointThreshold2         = 0x60,
        OnVictoryPointThreshold3         = 0x61,
        OnVictoryPointThreshold4         = 0x62,
    }
}