using System;
namespace SiphoningStrike
{
    public enum GamePacketID
    {
        Unused_Dummy                             = 0x000, // Done
        Unused_SPM_HierarchicalProfilerUpdate    = 0x001, // Done
        S2C_DisplayLocalizedTutorialChatText     = 0x002, // Done
        Barrack_SpawnUnit                        = 0x003, // Done
        S2C_SwitchNexusesToOnIdleParticles       = 0x004, // Done
        C2S_TutorialAudioEventFinished           = 0x005, // Done
        S2C_SetCircularMovementRestriction       = 0x006, // Done
        UpdateGoldRedirectTarget                 = 0x007, // Done
        SynchSimTimeC2S                          = 0x008, // Done
        RemoveItemReq                            = 0x009, // Done
        ResumePacket                             = 0x00A, // Done
        RemoveItemAns                            = 0x00B, // Done
        Unused_PKT32                             = 0x00C, // Done
        Basic_Attack                             = 0x00D, // 
        S2C_RefreshObjectiveText                 = 0x00E, // 
        S2C_CloseShop                            = 0x00F, // 
        S2C_Reconnect                            = 0x010, // 
        UnitAddEXP                               = 0x011, // 
        S2C_EndSpawn                             = 0x012, // 
        SetFrequency                             = 0x013, // 
        S2C_HighlightTitanBarElement             = 0x014, // 
        S2C_BotAI                                = 0x015, // 
        S2C_TeamSurrenderCountDown               = 0x016, // 
        C2S_QueryStatusReq                       = 0x017, // 
        NPC_UpgradeSpellAns                      = 0x018, // 
        C2S_Ping_Load_Info                       = 0x019, // 
        ChangeSlotSpellType                      = 0x01A, // 
        NPC_MessageToClient                      = 0x01B, // 
        DisplayFloatingText                      = 0x01C, // 
        Basic_Attack_Pos                         = 0x01D, // 
        NPC_ForceDead                            = 0x01E, // 
        NPC_BuffUpdateCount                      = 0x01F, // 
        C2S_WriteNavFlags_Acc                    = 0x020, // 
        NPC_BuffReplaceGroup                     = 0x021, // 
        NPC_SetAutocast                          = 0x022, // 
        SwapItemReq                              = 0x023, // 
        NPC_Die_EventHistroy                     = 0x024, // 
        UnitAddGold                              = 0x025, // 
        AddUnitPerceptionBubble                  = 0x026, // 
        S2C_MoveCameraToPoint                    = 0x027, // 
        S2C_LineMissileHitList                   = 0x028, // 
        S2C_MuteVolumeCategory                   = 0x029, // 
        ServerTick                               = 0x02A, // 
        S2C_StopAnimation                        = 0x02B, // 
        AvatarInfo_Server                        = 0x02C, // 
        DampenerSwitch                           = 0x02D, // 
        World_SendCamera_Server_Acknologment     = 0x02E, // 
        S2C_ModifyDebugCircleRadius              = 0x02F, // 
        World_SendCamera_Server                  = 0x030, // 
        HeroReincarnateAlive                     = 0x031, // 
        NPC_BuffReplace                          = 0x032, // 
        Pause                                    = 0x033, // 
        SetFadeOut_Pop                           = 0x034, // 
        ChangeSlotSpellName                      = 0x035, // 
        ChangeSlotSpellIcon                      = 0x036, // 
        ChangeSlotSpellOffsetTarget              = 0x037, // 
        RemovePerceptionBubble                   = 0x038, // 
        NPC_InstantStop_Attack                   = 0x039, // 
        OnLeaveLocalVisiblityClient              = 0x03A, // 
        S2C_ShowObjectiveText                    = 0x03B, // 
        CHAR_SpawnPet                            = 0x03C, // 
        FX_Kill                                  = 0x03D, // 
        NPC_UpgradeSpellReq                      = 0x03E, // 
        UseObjectC2S                             = 0x03F, // 
        Turret_CreateTurret                      = 0x040, // 
        MissileReplication                       = 0x041, // 
        ResetForSlowLoader                       = 0x042, // 
        S2C_HighlightHUDElement                  = 0x043, // 
        SwapItemAns                              = 0x044, // 
        NPC_LevelUp                              = 0x045, // 
        S2C_MapPing                              = 0x046, // 
        S2C_WriteNavFlags                        = 0x047, // 
        S2C_PlayEmote                            = 0x048, // 
        S2C_Reconnect_Done                       = 0x049, // 
        S2C_OnEventWorld                         = 0x04A, // 
        S2C_HeroStats                            = 0x04B, // 
        C2S_PlayEmote                            = 0x04C, // 
        HeroReincarnate                          = 0x04D, // 
        C2S_OnScoreBoardOpened                   = 0x04E, // 
        S2C_CreateHero                           = 0x04F, // 
        Unused_SPM_AddMemoryListener             = 0x050, // Done
        Unused_SPM_HierarchicalMemoryUpdate      = 0x051, // Done
        S2C_ToggleUIHighlight                    = 0x052, // 
        S2C_FaceDirection                        = 0x053, // 
        OnLeaveVisiblityClient                   = 0x054, // 
        C2S_ClientReady                          = 0x055, // 
        SetItem                                  = 0x056, // 
        SynchVersionS2C                          = 0x057, // 
        S2C_HandleTipUpdate                      = 0x058, // 
        C2S_StatsUpdateReq                       = 0x059, // 
        C2S_MapPing                              = 0x05A, // 
        S2C_RemoveDebugCircle                    = 0x05B, // 
        S2C_CreateUnitHighlight                  = 0x05C, // 
        S2C_DestroyClientMissile                 = 0x05D, // 
        S2C_LevelUpSpell                         = 0x05E, // 
        S2C_StartGame                            = 0x05F, // 
        C2S_OnShopOpened                         = 0x060, // 
        NPC_Hero_Die                             = 0x061, // 
        S2C_FadeOutMainSFX                       = 0x062, // 
        UserMessagesStart                        = 0x063, // 
        WaypointGroup                            = 0x064, // 
        S2C_StartSpawn                           = 0x065, // 
        S2C_CreateNeutral                        = 0x066, // 
        WaypointGroupWithSpeed                   = 0x067, // 
        UnitApplyDamage                          = 0x068, // 
        ModifyShield                             = 0x069, // 
        S2C_PopCharacterData                     = 0x06A, // 
        NPC_BuffAddGroup                         = 0x06B, // 
        S2C_AI_TargetSelection                   = 0x06C, // 
        AI_TargetS2C                             = 0x06D, // 
        S2C_SetAnimStates                        = 0x06E, // 
        S2C_ChainMissileSync                     = 0x06F, // 
        C2S_OnTipEvent                           = 0x070, // 
        MissileReplication_ChainMissile          = 0x071, // 
        BuyItemAns                               = 0x072, // 
        S2C_SetSpellData                         = 0x073, // 
        S2C_PauseAnimation                       = 0x074, // 
        NPC_IssueOrderReq                        = 0x075, // 
        S2C_CameraBehavior                       = 0x076, // 
        S2C_AnimatedBuildingSetCurrentSkin       = 0x077, // 
        Connected                                = 0x078, // 
        SyncSimTimeFinalS2C                      = 0x079, // 
        Waypoint_Acc                             = 0x07A, // 
        AddPosPerceptionBubble                   = 0x07B, // 
        S2C_LockCamera                           = 0x07C, // 
        S2C_PlayVOAudioEvent                     = 0x07D, // 
        AI_Command                               = 0x07E, // 
        NPC_BuffRemove2                          = 0x07F, // 
        SpawnMinionS2C                           = 0x080, // 
        ClientCheatDetectionSignal               = 0x081, // 
        S2C_ToggleFoW                            = 0x082, // 
        S2C_ToolTipVars                          = 0x083, // 
        UnitApplyHeal                            = 0x084, // 
        GlobalCombatMessage                      = 0x085, // 
        World_LockCamera_Server                  = 0x086, // 
        BuyItemReq                               = 0x087, // 
        WaypointListHeroWithSpeed                = 0x088, // 
        S2C_SetInputLockingFlag                  = 0x089, // 
        CHAR_SetCooldown                         = 0x08A, // 
        CHAR_CancelTargetingReticle              = 0x08B, // 
        FX_Create_Group                          = 0x08C, // 
        S2C_QueryStatusAns                       = 0x08D, // 
        Building_Die                             = 0x08E, // 
        Unused_SPM_RemoveListener                = 0x08F, // Done
        S2C_HandleQuestUpdate                    = 0x090, // 
        C2S_ClientFinished                       = 0x091, // 
        CHAT                                     = 0x092, // 
        Unused_SPM_RemoveMemoryListener          = 0x093, // Done
        C2S_Exit                                 = 0x094, // 
        ServerGameSettings                       = 0x095, // 
        S2C_ModifyDebugCircleColor               = 0x096, // 
        Unused_SPM_AddListener                   = 0x097, // Done
        World_SendGameNumber                     = 0x098, // 
        ChangePARColorOverride                   = 0x099, // 
        C2S_ClientConnect_NamedPipe              = 0x09A, // 
        NPC_BuffRemoveGroup                      = 0x09B, // 
        Turret_Fire                              = 0x09C, // 
        S2C_Ping_Load_Info                       = 0x09D, // 
        S2C_ChangeCharacterVoice                 = 0x09E, // 
        S2C_ChangeCharacterData                  = 0x09F, // 
        S2C_Exit                                 = 0x0A0, // 
        Unused_SPM_RemoveBBProfileListener       = 0x0A1, // Done
        NPC_CastSpellReq                         = 0x0A2, // 
        S2C_ToggleInputLockingFlag               = 0x0A3, // 
        C2S_Reconnect                            = 0x0A4, // 
        S2C_CreateTurret                         = 0x0A5, // 
        NPC_Die                                  = 0x0A6, // 
        UseItemAns                               = 0x0A7, // 
        S2C_ShowAuxiliaryText                    = 0x0A8, // 
        PausePacket                              = 0x0A9, // 
        S2C_HideObjectiveText                    = 0x0AA, // 
        OnEvent                                  = 0x0AB, // 
        C2S_TeamSurrenderVote                    = 0x0AC, // 
        S2C_TeamSurrenderStatus                  = 0x0AD, // 
        Unused_SPM_AddBBProfileListener          = 0x0AE, // Done
        S2C_HideAuxiliaryText                    = 0x0AF, // 
        OnReplication_Acc                        = 0x0B0, // 
        OnDisconnected                           = 0x0B1, // 
        S2C_SetGreyscaleEnabledWhenDead          = 0x0B2, // 
        S2C_AI_State                             = 0x0B3, // 
        S2C_SetFoWStatus                         = 0x0B4, // 
        OnEnterLocalVisiblityClient              = 0x0B5, // 
        S2C_HighlightShopElement                 = 0x0B6, // 
        SendSelectedObjID                        = 0x0B7, // 
        S2C_PlayAnimation                        = 0x0B8, // 
        S2C_RefreshAuxiliaryText                 = 0x0B9, // 
        SetFadeOut_Push                          = 0x0BA, // 
        S2C_OpenTutorialPopup                    = 0x0BB, // 
        S2C_RemoveUnitHighlight                  = 0x0BC, // 
        NPC_CastSpellAns                         = 0x0BD, // 
        Unused_SPM_HierarchicalBBProfileUpdate   = 0x0BE, // Done
        NPC_BuffAdd2                             = 0x0BF, // 
        S2C_OpenAFKWarningMessage                = 0x0C0, // 
        WaypointList                             = 0x0C1, // 
        OnEnterVisiblityClient                   = 0x0C2, // 
        S2C_AddDebugCircle                       = 0x0C3, // 
        S2C_DisableHUDForEndOfGame               = 0x0C4, // 
        SynchVersionC2S                          = 0x0C5, // 
        C2S_CharSelected                         = 0x0C6, // 
        NPC_BuffUpdateCountGroup                 = 0x0C7, // 
        AI_TargetHeroS2C                         = 0x0C8, // 
        SynchSimTimeS2C                          = 0x0C9, // 
        SyncMissionStartTimeS2C                  = 0x0CA, // 
        S2C_Neutral_Camp_Empty                   = 0x0CB, // 
        OnReplication                            = 0x0CC, // 
        S2C_EndOfGameEvent                       = 0x0CD, // 
        S2C_EndGame                              = 0x0CE, // 
        Unused_Undefined                         = 0x0CF, // Done
        Unused_SPM_SamplingProfilerUpdate        = 0x0D0, // Done
        S2C_PopAllCharacterData                  = 0x0D1, // 
        S2C_TeamSurrenderVote                    = 0x0D2, // 
        S2C_HandleUIHighlight                    = 0x0D3, // 
        S2C_FadeMinions                          = 0x0D4, // 
        C2S_OnTutorialPopupClosed                = 0x0D5, // 
        C2S_OnQuestEvent                         = 0x0D6, // 
        S2C_ShowHealthBar                        = 0x0D7, // 
        SpawnBotS2C                              = 0x0D8, // 
        SpawnLevelPropS2C                        = 0x0D9, // 
        UpdateLevelPropS2C                       = 0x0DA, // 
        AttachFlexParticleS2C                    = 0x0DB, // 
        S2C_HandleCapturePointUpdate             = 0x0DC, // 
        S2C_HandleGameScore                      = 0x0DD, // 
        S2C_HandleRespawnPointUpdate             = 0x0DE, // 
        C2S_OnRespawnPointEvent                  = 0x0DF, // 
        S2C_UnitChangeTeam                       = 0x0E0, // 
        S2C_UnitSetMinimapIcon                   = 0x0E1, // 
        S2C_IncrementPlayerScore                 = 0x0E2, // 
        S2C_IncrementPlayerStat                  = 0x0E3, // 
        S2C_ColorRemapFX                         = 0x0E4, // 
        S2C_MusicCueCommand                      = 0x0E5, // 
        Unused_S2C_AntiBot                       = 0x0E6, // Done
        Unused_S2C_AntiBotWriteLog               = 0x0E7, // Done
        Unused_S2C_AntiBotKickOut                = 0x0E8, // Done
        Unused_S2C_AntiBotBanPlayer              = 0x0E9, // Done
        Unused_S2C_AntiBotTrojan                 = 0x0EA, // Done
        Unused_S2C_AntiBotCloseClient            = 0x0EB, // Done
        Unused_C2S_AntiBotDP                     = 0x0EC, // Done
        Unused_ED                                = 0x0ED, // Done
        S2C_OnEnterTeamVisiblity                 = 0x0EE, // 
        S2C_OnLeaveTeamVisiblity                 = 0x0EF, // 
        S2C_FX_OnEnterTeamVisiblity              = 0x0F0, // 
        S2C_FX_OnLeaveTeamVisiblity              = 0x0F1, // 
        ReplayOnly_GoldEarned                    = 0x0F2, // 

        Batch                                    = 0x0FF, //
    }
}
